### ISSUE TITLE
therubyracer vs node memory usage?

### ISSUE THREAD

**Issue by sfcgeorge** [ruby-hyperloop/hyperloop#11]
Heroku [advises not to use therubyracer](https://devcenter.heroku.com/articles/rails-asset-pipeline#therubyracer) and use Node instead as therubyracer uses lots of memory. Could Hyperloop use Node on the backend instead? I'm not entirely sure what it's being used for.

**Comment by catmando** [comment]
This will be addressed in the base hyper-react / hyper-component gem.  We will be using mini racer which is much better. (See https://github.com/ruby-hyperloop/hyper-react/issues/230)

The problem with specifically using Node is that during pre-rerendering we have 2 way communication between client and server, and we would have to emulate this somehow, which is in fact what things like ruby-racer and mini-racer do.
